"""Initial migration with all models

Revision ID: b6a562171675
Revises: 
Create Date: 2025-12-31 15:15:08.438346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a562171675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('news_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('political_bias', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fetch_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_sources'))
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], name=op.f('fk_articles_source_id_news_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('url', name=op.f('uq_articles_url'))
    )
    op.create_index('ix_articles_hash', 'articles', ['content_hash'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_source', 'articles', ['source_id'], unique=False)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_index('ix_articles_url', 'articles', ['url'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('is_checkable', sa.Boolean(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_claims_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_article', 'claims', ['article_id'], unique=False)
    op.create_index('ix_claims_checkable', 'claims', ['is_checkable'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['status'], unique=False)
    op.create_index('ix_claims_type', 'claims', ['claim_type'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('propaganda_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_reliability_avg', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('supporting_evidence_count', sa.Integer(), nullable=True),
    sa.Column('refuting_evidence_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_investigations_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index('ix_investigations_claim', 'investigations', ['claim_id'], unique=False)
    op.create_index('ix_investigations_confidence', 'investigations', ['confidence_score'], unique=False)
    op.create_index('ix_investigations_status', 'investigations', ['status'], unique=False)
    op.create_index('ix_investigations_verdict', 'investigations', ['verdict'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_reliability', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('stance', sa.String(length=50), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_evidence_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_investigation', 'evidence', ['investigation_id'], unique=False)
    op.create_index('ix_evidence_relevance', 'evidence', ['relevance_score'], unique=False)
    op.create_index('ix_evidence_reliability', 'evidence', ['source_reliability'], unique=False)
    op.create_index('ix_evidence_stance', 'evidence', ['stance'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_stance', table_name='evidence')
    op.drop_index('ix_evidence_reliability', table_name='evidence')
    op.drop_index('ix_evidence_relevance', table_name='evidence')
    op.drop_index('ix_evidence_investigation', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_investigations_verdict', table_name='investigations')
    op.drop_index('ix_investigations_status', table_name='investigations')
    op.drop_index('ix_investigations_confidence', table_name='investigations')
    op.drop_index('ix_investigations_claim', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_claims_type', table_name='claims')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index('ix_claims_checkable', table_name='claims')
    op.drop_index('ix_claims_article', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_articles_url', table_name='articles')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_source', table_name='articles')
    op.drop_index('ix_articles_published', table_name='articles')
    op.drop_index('ix_articles_hash', table_name='articles')
    op.drop_table('articles')
    op.drop_table('news_sources')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
